name: CI/CD for Todo App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      status:
        description: 'Jenkins build status (success/failure)'
        required: true
        type: string

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test --if-present

  build-and-push-docker:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.status == 'success' }}  # Only run this if Jenkins build is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t wostez/todo-app:latest .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push wostez/todo-app:latest
          
      - name: Docker image pushed to Docker Hub
        run: echo "Docker image pushed to Docker Hub successfully!"

  failure-message:
    if: ${{ github.event.inputs.status != 'success' }}  # Show failure message if Jenkins build failed
    runs-on: ubuntu-latest
    steps:
      - name: Build failed
        run: echo "Jenkins build failed. Docker image will not be pushed."
